/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajo_practico;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class LoginScreen extends javax.swing.JPanel {
    bdOracle bd = new bdOracle();
    static JFrame frame = new JFrame("Iniciar Sesión");
    
    public LoginScreen() {
        initComponents();
        lpSecondary.setSize(350, 350);
        lpSecondary.setOpaque(true);
        lTitulo.setOpaque(true);
        tfUser.setBorder(BorderFactory.createCompoundBorder(
        tfUser.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pfPass.setBorder(BorderFactory.createCompoundBorder(
        pfPass.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        lError.setVisible(false);
    }
    
    public void login() {
        String username = tfUser.getText();
        String password = String.valueOf(pfPass.getPassword());;
        
        try {
            bd.abrir(username, password);
            frame.dispose();
            CrudEmpresa fEmpresa = new CrudEmpresa(bd);
            fEmpresa.run();
        } catch (SQLException ex) {
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
            lError.setVisible(true);
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        Color color1 = new Color(84, 52, 178);
        Color color2 = new Color(172, 95, 200);
        GradientPaint gp = new GradientPaint(0, 0, color1, 0, h, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                LoginScreen panel = new LoginScreen();
                frame.add(panel);
                frame.setSize(400, 400);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        lpSecondary = new javax.swing.JLayeredPane();
        pForm = new javax.swing.JPanel();
        lUser = new javax.swing.JLabel();
        lClave = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        pfPass = new javax.swing.JPasswordField();
        cbShowPass = new javax.swing.JCheckBox();
        pButtons = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        bSubmit = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lError = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 400));

        lpSecondary.setBackground(new java.awt.Color(255, 255, 255));
        lpSecondary.setPreferredSize(new java.awt.Dimension(330, 350));

        pForm.setBackground(new java.awt.Color(255, 255, 255));

        lUser.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lUser.setText("Usuario");

        lClave.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lClave.setText("Clave");

        tfUser.setBackground(new java.awt.Color(229, 232, 237));
        tfUser.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tfUser.setBorder(null);
        tfUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pfPass.setBackground(new java.awt.Color(229, 232, 237));
        pfPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pfPass.setBorder(null);
        pfPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbShowPass.setBackground(new java.awt.Color(255, 255, 255));
        cbShowPass.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        cbShowPass.setText("Mostrar Código");
        cbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFormLayout = new javax.swing.GroupLayout(pForm);
        pForm.setLayout(pFormLayout);
        pFormLayout.setHorizontalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormLayout.createSequentialGroup()
                .addGroup(pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFormLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(cbShowPass))
                    .addGroup(pFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lUser)))
                    .addGroup(pFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lClave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        pFormLayout.setVerticalGroup(
            pFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbShowPass)
                .addContainerGap())
        );

        pButtons.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pButtonsLayout = new javax.swing.GroupLayout(pButtons);
        pButtons.setLayout(pButtonsLayout);
        pButtonsLayout.setHorizontalGroup(
            pButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pButtonsLayout.setVerticalGroup(
            pButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        lTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("ACCESO AL SISTEMA");
        lTitulo.setToolTipText("");
        lTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lTitulo.setMaximumSize(new java.awt.Dimension(350, 10));
        lTitulo.setMinimumSize(new java.awt.Dimension(350, 10));

        bSubmit.setBackground(new java.awt.Color(255, 255, 255));
        bSubmit.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        bSubmit.setText("Aceptar");
        bSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 95, 200)));
        bSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSubmit.setFocusPainted(false);
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        bExit.setBackground(new java.awt.Color(255, 255, 255));
        bExit.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        bExit.setText("Salir");
        bExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        bExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExit.setFocusPainted(false);
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/key.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lError.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lError.setForeground(new java.awt.Color(255, 0, 0));
        lError.setText("Usuario o clave inválidos. Acceso Denegado. ");

        lpSecondary.setLayer(pForm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(pButtons, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bSubmit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bExit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lError, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpSecondaryLayout = new javax.swing.GroupLayout(lpSecondary);
        lpSecondary.setLayout(lpSecondaryLayout);
        lpSecondaryLayout.setHorizontalGroup(
            lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSecondaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpSecondaryLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lError, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpSecondaryLayout.createSequentialGroup()
                        .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(lpSecondaryLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpSecondaryLayout.createSequentialGroup()
                                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        lpSecondaryLayout.setVerticalGroup(
            lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSecondaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(lError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSubmit)
                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lpSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lpSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
       login(); 
    }//GEN-LAST:event_bSubmitActionPerformed

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        if(cbShowPass.isSelected()) {
            pfPass.setEchoChar((char)0);
        } else {
            pfPass.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bSubmit;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lClave;
    private javax.swing.JLabel lError;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lUser;
    private javax.swing.JLayeredPane lpSecondary;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pForm;
    private javax.swing.JPasswordField pfPass;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
