package forms;

/**
 *
 * @author Nelba Barreto
 */

import db.bdOracle;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import models.Empresa;
import models.FacturaProvDet;
import utils.Formulario;

public class Main extends javax.swing.JFrame {
    private List<Empresa> empresas;
    private List<FacturaProvDet> facturasProvDet;
    private static bdOracle conexion;
    private String msg;

    public Main(bdOracle bd) {
        conexion = bd;
        initComponents();
    }
    
    public void run() {
        new Main(conexion).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UIManager.put("TabbedPane.selected", new Color(229, 232, 237));
        tabPrimary = new javax.swing.JTabbedPane();
        pParametros = new javax.swing.JPanel();
        TabSecondary = new javax.swing.JTabbedPane();
        pEmpresas = new javax.swing.JPanel();
        lId = new javax.swing.JLabel();
        lId1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lEmpresa = new javax.swing.JList<>();
        bCreate1 = new javax.swing.JButton();
        bUpdate1 = new javax.swing.JButton();
        bDelete1 = new javax.swing.JButton();
        lMsg1 = new javax.swing.JLabel();
        pProductos = new javax.swing.JPanel();
        pMantenimientos = new javax.swing.JPanel();
        pMSecondary = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pRecepciones = new javax.swing.JPanel();
        pFacturaProv = new javax.swing.JPanel();
        laEmpresa = new javax.swing.JLabel();
        cxEmpresa = new javax.swing.JComboBox<>();
        lNroFactProv = new javax.swing.JLabel();
        tfNroFactProv = new javax.swing.JTextField();
        lFecha = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        lEstado = new javax.swing.JLabel();
        cxEstado = new javax.swing.JComboBox<>();
        lTipoFactura = new javax.swing.JLabel();
        cxTipoFactura = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tFacturaProvDet = new javax.swing.JTable();
        lEstado1 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        bCreate = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bConsultar = new javax.swing.JButton();
        lMsg = new javax.swing.JLabel();
        bClean = new javax.swing.JButton();
        pCaja = new javax.swing.JPanel();
        pCSecondary = new javax.swing.JTabbedPane();
        pFacturaVenta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPrimary.setBackground(new java.awt.Color(255, 255, 255));
        tabPrimary.setToolTipText("");
        tabPrimary.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tabPrimary.setOpaque(true);

        TabSecondary.setBackground(new java.awt.Color(255, 255, 255));
        TabSecondary.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        pEmpresas.setBackground(new java.awt.Color(255, 255, 255));

        lId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lId.setText("Id Empresa");

        lId1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lId1.setText("Descripción");

        tfId.setBackground(new java.awt.Color(229, 232, 237));
        tfId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tfId.setBorder(null);
        tfId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfId.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfId.setEnabled(false);
        tfId.setBorder(BorderFactory.createCompoundBorder(
            tfId.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

    tfDescripcion.setBackground(new java.awt.Color(229, 232, 237));
    tfDescripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tfDescripcion.setBorder(null);
    tfDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tfDescripcion.setBorder(BorderFactory.createCompoundBorder(
        tfDescripcion.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

lEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(172, 95, 200), 1, true));
lEmpresa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
lEmpresa.setSelectionBackground(new java.awt.Color(229, 232, 237));
lEmpresa.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
    public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        lEmpresaValueChanged(evt);
    }
    });
    empresas = Formulario.Empresas.populateList(lEmpresa, conexion);
    jScrollPane1.setViewportView(lEmpresa);

    bCreate1.setBackground(new java.awt.Color(255, 255, 255));
    bCreate1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bCreate1.setText("Insertar");
    bCreate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bCreate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bCreate1.setFocusPainted(false);
    bCreate1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bCreate1ActionPerformed(evt);
        }
    });

    bUpdate1.setBackground(new java.awt.Color(255, 255, 255));
    bUpdate1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bUpdate1.setText("Actualizar");
    bUpdate1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bUpdate1.setFocusPainted(false);
    bUpdate1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bUpdate1ActionPerformed(evt);
        }
    });

    bDelete1.setBackground(new java.awt.Color(255, 255, 255));
    bDelete1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bDelete1.setText("Eliminar");
    bDelete1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bDelete1.setFocusPainted(false);
    bDelete1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bDelete1ActionPerformed(evt);
        }
    });

    lMsg1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

    javax.swing.GroupLayout pEmpresasLayout = new javax.swing.GroupLayout(pEmpresas);
    pEmpresas.setLayout(pEmpresasLayout);
    pEmpresasLayout.setHorizontalGroup(
        pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pEmpresasLayout.createSequentialGroup()
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfId)
                        .addComponent(tfDescripcion)
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lId1)
                                .addComponent(lId))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(50, 50, 50))
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(bCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27))
    );
    pEmpresasLayout.setVerticalGroup(
        pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pEmpresasLayout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addComponent(lId)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)
                    .addComponent(lId1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1))
            .addContainerGap(43, Short.MAX_VALUE))
    );

    TabSecondary.addTab("Empresas", pEmpresas);

    javax.swing.GroupLayout pProductosLayout = new javax.swing.GroupLayout(pProductos);
    pProductos.setLayout(pProductosLayout);
    pProductosLayout.setHorizontalGroup(
        pProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 565, Short.MAX_VALUE)
    );
    pProductosLayout.setVerticalGroup(
        pProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 359, Short.MAX_VALUE)
    );

    TabSecondary.addTab("Productos", pProductos);

    javax.swing.GroupLayout pParametrosLayout = new javax.swing.GroupLayout(pParametros);
    pParametros.setLayout(pParametrosLayout);
    pParametrosLayout.setHorizontalGroup(
        pParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(TabSecondary, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    pParametrosLayout.setVerticalGroup(
        pParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(TabSecondary)
    );

    tabPrimary.addTab("PARÁMETROS", pParametros);

    pMSecondary.setBackground(new java.awt.Color(255, 255, 255));
    pMSecondary.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    pMSecondary.setVerifyInputWhenFocusTarget(false);

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    pMSecondary.addTab("Personas", jPanel2);

    pRecepciones.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout pRecepcionesLayout = new javax.swing.GroupLayout(pRecepciones);
    pRecepciones.setLayout(pRecepcionesLayout);
    pRecepcionesLayout.setHorizontalGroup(
        pRecepcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    pRecepcionesLayout.setVerticalGroup(
        pRecepcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    pMSecondary.addTab("Recepciones", pRecepciones);

    pFacturaProv.setBackground(new java.awt.Color(255, 255, 255));

    laEmpresa.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    laEmpresa.setText("Empresa");

    cxEmpresa.setBackground(new java.awt.Color(229, 232, 237));
    cxEmpresa.setPreferredSize(new java.awt.Dimension(1, 15));
    empresas = Formulario.Empresas.populateComboBox(cxEmpresa, conexion);

    lNroFactProv.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    lNroFactProv.setText("Nro. Factura Prov.");

    tfNroFactProv.setBackground(new java.awt.Color(229, 232, 237));
    tfNroFactProv.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tfNroFactProv.setBorder(null);
    tfNroFactProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tfNroFactProv.setDisabledTextColor(new java.awt.Color(51, 51, 51));
    tfNroFactProv.setBorder(BorderFactory.createCompoundBorder(
        tfNroFactProv.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

lFecha.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
lFecha.setText("Fecha");

tfFecha.setBackground(new java.awt.Color(229, 232, 237));
tfFecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
tfFecha.setBorder(null);
tfFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
tfFecha.setDisabledTextColor(new java.awt.Color(51, 51, 51));
tfFecha.setBorder(BorderFactory.createCompoundBorder(
    tfFecha.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

    lEstado.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    lEstado.setText("Estado");

    cxEstado.setBackground(new java.awt.Color(229, 232, 237));
    cxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "CANCELADO", "ANULADO" }));
    cxEstado.setToolTipText("");
    cxEstado.setPreferredSize(new java.awt.Dimension(1, 15));

    lTipoFactura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    lTipoFactura.setText("Tipo Factura");

    cxTipoFactura.setBackground(new java.awt.Color(229, 232, 237));
    cxTipoFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTADO", "CRÉDITO" }));
    cxTipoFactura.setPreferredSize(new java.awt.Dimension(1, 15));

    tFacturaProvDet.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tFacturaProvDet.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Ítem", "Producto", "Descripción", "Cantidad", "Importe"
        }
    ));
    jScrollPane2.setViewportView(tFacturaProvDet);

    lEstado1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    lEstado1.setText("Total");

    tfTotal.setBackground(new java.awt.Color(229, 232, 237));
    tfTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tfTotal.setBorder(null);
    tfTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tfTotal.setDisabledTextColor(new java.awt.Color(51, 51, 51));
    tfTotal.setEnabled(false);
    tfTotal.setBorder(BorderFactory.createCompoundBorder(
        tfTotal.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

bCreate.setBackground(new java.awt.Color(255, 255, 255));
bCreate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
bCreate.setText("Insertar");
bCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
bCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
bCreate.setFocusPainted(false);
bCreate.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        bCreateActionPerformed(evt);
    }
    });

    bUpdate.setBackground(new java.awt.Color(255, 255, 255));
    bUpdate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bUpdate.setText("Actualizar");
    bUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bUpdate.setFocusPainted(false);
    bUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bUpdateActionPerformed(evt);
        }
    });

    bDelete.setBackground(new java.awt.Color(255, 255, 255));
    bDelete.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bDelete.setText("Eliminar");
    bDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bDelete.setFocusPainted(false);
    bDelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bDeleteActionPerformed(evt);
        }
    });

    bConsultar.setBackground(new java.awt.Color(255, 255, 255));
    bConsultar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bConsultar.setText("Consultar");
    bConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bConsultar.setFocusPainted(false);
    bConsultar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bConsultarActionPerformed(evt);
        }
    });

    lMsg.setText("jLabel1");

    bClean.setBackground(new java.awt.Color(255, 255, 255));
    bClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/broom.png"))); // NOI18N
    bClean.setToolTipText("Limpiar");
    bClean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 95, 200)));
    bClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bClean.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bCleanActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout pFacturaProvLayout = new javax.swing.GroupLayout(pFacturaProv);
    pFacturaProv.setLayout(pFacturaProvLayout);
    pFacturaProvLayout.setHorizontalGroup(
        pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pFacturaProvLayout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pFacturaProvLayout.createSequentialGroup()
                    .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pFacturaProvLayout.createSequentialGroup()
                            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pFacturaProvLayout.createSequentialGroup()
                                    .addComponent(lNroFactProv)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfNroFactProv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pFacturaProvLayout.createSequentialGroup()
                                    .addComponent(lEstado)
                                    .addGap(18, 18, 18)
                                    .addComponent(cxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lFecha, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lTipoFactura, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(26, 26, 26)
                            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cxTipoFactura, 0, 186, Short.MAX_VALUE)
                                .addComponent(tfFecha)))
                        .addComponent(jScrollPane2)
                        .addGroup(pFacturaProvLayout.createSequentialGroup()
                            .addComponent(lMsg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEstado1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(23, 23, 23))
                .addGroup(pFacturaProvLayout.createSequentialGroup()
                    .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pFacturaProvLayout.createSequentialGroup()
                            .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pFacturaProvLayout.createSequentialGroup()
                            .addComponent(laEmpresa)
                            .addGap(18, 18, 18)
                            .addComponent(cxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bClean)))
                    .addContainerGap(22, Short.MAX_VALUE))))
    );
    pFacturaProvLayout.setVerticalGroup(
        pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pFacturaProvLayout.createSequentialGroup()
            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pFacturaProvLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(laEmpresa)
                        .addComponent(cxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFacturaProvLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bClean)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfNroFactProv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lNroFactProv)
                .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(17, 17, 17)
            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cxTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lTipoFactura)
                .addComponent(lEstado))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lEstado1)
                .addComponent(lMsg))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pFacturaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(21, Short.MAX_VALUE))
    );

    bClean.getAccessibleContext().setAccessibleDescription("Limpiar");

    pMSecondary.addTab("Factura Proveedor", pFacturaProv);

    javax.swing.GroupLayout pMantenimientosLayout = new javax.swing.GroupLayout(pMantenimientos);
    pMantenimientos.setLayout(pMantenimientosLayout);
    pMantenimientosLayout.setHorizontalGroup(
        pMantenimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pMSecondary, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    pMantenimientosLayout.setVerticalGroup(
        pMantenimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pMSecondary)
    );

    tabPrimary.addTab("MANTENIMIENTO", pMantenimientos);

    pCSecondary.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

    javax.swing.GroupLayout pFacturaVentaLayout = new javax.swing.GroupLayout(pFacturaVenta);
    pFacturaVenta.setLayout(pFacturaVentaLayout);
    pFacturaVentaLayout.setHorizontalGroup(
        pFacturaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 565, Short.MAX_VALUE)
    );
    pFacturaVentaLayout.setVerticalGroup(
        pFacturaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 359, Short.MAX_VALUE)
    );

    pCSecondary.addTab("Factura Venta", pFacturaVenta);

    javax.swing.GroupLayout pCajaLayout = new javax.swing.GroupLayout(pCaja);
    pCaja.setLayout(pCajaLayout);
    pCajaLayout.setHorizontalGroup(
        pCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pCSecondary, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    pCajaLayout.setVerticalGroup(
        pCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(pCSecondary)
    );

    tabPrimary.addTab("CAJA", pCaja);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabPrimary, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabPrimary, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    tabPrimary.getAccessibleContext().setAccessibleName("");

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        try {
            // Id Empresa
            int index = cxEmpresa.getSelectedIndex();
            int idEmpresa = empresas.get(index).getId();
            // Fecha
            String fecha = tfFecha.getText();
            // Estado (1. ACTIVO, 2. CANCELADO, 3. ANULADO )
            int estado = cxEstado.getSelectedIndex() + 1;
            // Tipo (1. CONTADO, 2. CREDITO)
            int tipo = cxTipoFactura.getSelectedIndex() + 1;

            int response = conexion.fc_inse_factura_prov(conexion.recuSigteNumero("FACTURAS_PROV"), 
                    fecha, estado, tipo, idEmpresa);
            if (response == 1) {
                msg = "Registro insertado correctamente";
            } else {
                msg = "No se pudo insertar el registro";
            }
            Formulario.Empresas.setMsg(response, lMsg, msg);
        } catch (Exception ex) {
            msg = "No se pudo insertar el registro";
            Formulario.Empresas.setMsg(0, lMsg, msg);
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        };
    }//GEN-LAST:event_bCreateActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        try {
            // Nro. Factura Proveedor
            int nroFacturaProv = Integer.parseInt(tfNroFactProv.getText());
            // Id Empresa
            int index = cxEmpresa.getSelectedIndex();
            int idEmpresa = empresas.get(index).getId();
            String fecha = tfFecha.getText();
            // Estado (1. ACTIVO, 2. CANCELADO, 3. ANULADO )
            int estado = cxEstado.getSelectedIndex() + 1;
            // Tipo (1. CONTADO, 2. CREDITO)
            int tipo = cxTipoFactura.getSelectedIndex() + 1;

            int response = conexion.fc_actu_factura_prov(nroFacturaProv, fecha, estado, tipo, idEmpresa);
            if (response == 1) {
                msg = "Registro actualizado correctamente";
            } else {
                msg = "No se pudo actualizar el registro";
            }
            Formulario.Empresas.setMsg(response, lMsg, msg);

            // Actualizar detalle
            for (int i = 0; i < tFacturaProvDet.getRowCount(); i++) {
                // Item, Cantidad, Importe, Nro_factura_prov, Cod_producto
                conexion.fc_actu_factura_prov_det(Integer.parseInt(tFacturaProvDet.getValueAt(i, 0).toString()),
                        Integer.parseInt(tFacturaProvDet.getValueAt(i, 3).toString()),
                        Integer.parseInt(tFacturaProvDet.getValueAt(i, 4).toString()),
                        nroFacturaProv,
                        Integer.parseInt(tFacturaProvDet.getValueAt(i, 1).toString()));
            }
        } catch (Exception ex) {
            msg = "No se pudo actualizar el registro";
            Formulario.Empresas.setMsg(0, lMsg, msg);
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        };
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        try {
            // Nro. Factura Proveedor
            int nroFacturaProv = Integer.parseInt(tfNroFactProv.getText());
            try {
                conexion.sql("DELETE FROM facturas_prov_det WHERE fpde_nro_factura_prov = " + nroFacturaProv);
            } catch (SQLException ex) {
                Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
            }
            int response = conexion.fc_dele_factura_prov(nroFacturaProv);
            if (response == 1) {
                msg = "Registro eliminado correctamente";
            } else {
                msg = "No se pudo eliminar el registro";
            }
            Formulario.Empresas.setMsg(response, lMsg, msg);
        } catch (SQLException ex) {
            msg = "No se pudo eliminar el registro";
            Formulario.Empresas.setMsg(0, lMsg, msg);
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            msg = "No se pudo eliminar el registro";
            Formulario.Empresas.setMsg(0, lMsg, msg);
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        };
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed
        try {
            if (tfNroFactProv.getText().equals("")) {
                msg = "Nro. Factura Prov. no puede estar vacío";
                Formulario.Empresas.setMsg(0, lMsg, msg);
            } else {
                // Nro. Factura Proveedor
                int nroFacturaProv = Integer.parseInt(tfNroFactProv.getText());
                String query = "SELECT fapr_nro_factura_prov, TO_CHAR(fapr_fecha, 'dd/mm/yyyy'), fapr_estado, "
                        + "fapr_tipo_factura, fapr_id_empresa FROM facturas_prov WHERE fapr_nro_factura_prov = " + nroFacturaProv;

                ResultSet rset = conexion.sql(query);
                
                if(Formulario.General.resultSetIsEmpty(rset) == true) {
                    msg = "No se encuentra ninguna Factura Proveedor con ese número";
                    Formulario.Empresas.setMsg(0, lMsg, msg);
                } else {
                    lMsg.setText("");
                    do { 
                        tfFecha.setText(rset.getString(2));
                        cxEstado.setSelectedIndex(rset.getInt(3) - 1);
                        cxTipoFactura.setSelectedIndex(rset.getInt(4) - 1);
                        cxEmpresa.setSelectedIndex(Formulario.Empresas.findEmpresa(rset.getInt(5), empresas));
                        facturasProvDet = Formulario.FacturasProvDet.populateTable(tFacturaProvDet, nroFacturaProv, conexion);
                        tfTotal.setText(String.valueOf(Formulario.FacturasProvDet.calcularTotal(facturasProvDet)));
                    } while (rset.next());
                }
            }
        } catch (SQLException ex) {
            msg = "Error al consultar";
            Formulario.Empresas.setMsg(0, lMsg, msg);
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            msg = "Error al consultar";
            Formulario.Empresas.setMsg(0, lMsg, msg);
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        };
    }//GEN-LAST:event_bConsultarActionPerformed

    private void lEmpresaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lEmpresaValueChanged
        if(lEmpresa.getSelectedValue() != null) {
            String descripcion = lEmpresa.getSelectedValue();
            int index = lEmpresa.getSelectedIndex();
            String id = String.valueOf(empresas.get(index).getId());

            tfId.setText(id);
            tfDescripcion.setText(descripcion);
        }
    }//GEN-LAST:event_lEmpresaValueChanged

    private void bCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreate1ActionPerformed
        try {
            String descripcion = tfDescripcion.getText();
            if(descripcion.equals("")) {
                msg = "El campo descripción no puede estar vacío";
                 Formulario.Empresas.setMsg(0, lMsg, msg);
            } else {
                int response = conexion.fc_inse_empresa(conexion.recuSigteNumero("EMPRESAS"), descripcion);
                if (response == 1) {
                    lEmpresa.clearSelection();
                    empresas = Formulario.Empresas.populateList(lEmpresa, conexion);
                    tfDescripcion.setText("");
                    tfId.setText("");
                    msg = "Registro insertado correctamente";
                } else {
                    msg = "No se pudo insertar el registro";
                }
                Formulario.Empresas.setMsg(response, lMsg, msg);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCreate1ActionPerformed

    private void bUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdate1ActionPerformed
        try {
            int id = Integer.parseInt(tfId.getText());
            String descripcion = tfDescripcion.getText();

            int response = conexion.fc_actu_empresa(id, descripcion);
            if (response == 1) {
                empresas = Formulario.Empresas.populateList(lEmpresa, conexion);
                msg = "Registro actualizado correctamente";
            } else {
                msg = "No se pudo actualizar el registro";
            }
            Formulario.Empresas.setMsg(response, lMsg, msg);
        } catch (SQLException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bUpdate1ActionPerformed

    private void bDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelete1ActionPerformed
        try {
            int id = Integer.parseInt(tfId.getText());

            int response = conexion.fc_dele_empresa(id);
            if (response == 1) {
                lEmpresa.clearSelection();
                empresas = Formulario.Empresas.populateList(lEmpresa, conexion);
                tfDescripcion.setText("");
                tfId.setText("");
                msg = "Registro eliminado correctamente";
            } else {
                msg = "No se pudo eliminar el registro";
            }
            Formulario.Empresas.setMsg(response, lMsg, msg);
        } catch (SQLException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDelete1ActionPerformed

    private void bCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCleanActionPerformed
       cxEmpresa.setSelectedIndex(0);
       tfNroFactProv.setText("");
       tfFecha.setText("");
       cxEstado.setSelectedIndex(0);
       cxTipoFactura.setSelectedIndex(0);
       facturasProvDet = Formulario.FacturasProvDet.clearTable(tFacturaProvDet);
       tfTotal.setText("");
    }//GEN-LAST:event_bCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabSecondary;
    private javax.swing.JButton bClean;
    private javax.swing.JButton bConsultar;
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bCreate1;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bDelete1;
    private javax.swing.JButton bUpdate;
    private javax.swing.JButton bUpdate1;
    private javax.swing.JComboBox<String> cxEmpresa;
    private javax.swing.JComboBox<String> cxEstado;
    private javax.swing.JComboBox<String> cxTipoFactura;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lEmpresa;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lEstado1;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lId1;
    private javax.swing.JLabel lMsg;
    private javax.swing.JLabel lMsg1;
    private javax.swing.JLabel lNroFactProv;
    private javax.swing.JLabel lTipoFactura;
    private javax.swing.JLabel laEmpresa;
    private javax.swing.JTabbedPane pCSecondary;
    private javax.swing.JPanel pCaja;
    private javax.swing.JPanel pEmpresas;
    private javax.swing.JPanel pFacturaProv;
    private javax.swing.JPanel pFacturaVenta;
    private javax.swing.JTabbedPane pMSecondary;
    private javax.swing.JPanel pMantenimientos;
    private javax.swing.JPanel pParametros;
    private javax.swing.JPanel pProductos;
    private javax.swing.JPanel pRecepciones;
    private javax.swing.JTable tFacturaProvDet;
    private javax.swing.JTabbedPane tabPrimary;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNroFactProv;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
