/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import db.bdOracle;
import forms.abm.Empresas;
import forms.abm.FacturasProv;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class MenuPrincipal extends javax.swing.JPanel {
    private final JFrame fMainMenu = new JFrame("Menú Principal");
    private final bdOracle conexion;
    private String msg;
    
    public MenuPrincipal(bdOracle bd) {
        conexion = bd;
        initComponents();
        lpSecondary.setSize(350, 350);
        lpSecondary.setOpaque(true);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        Color color1 = new Color(84, 52, 178);
        Color color2 = new Color(172, 95, 200);
        GradientPaint gp = new GradientPaint(0, 0, color1, 0, h, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
    }

    public void run() {
        MenuPrincipal panel = new MenuPrincipal(conexion);
        fMainMenu.add(panel);
        fMainMenu.setSize(400, 400);
        fMainMenu.setLocationRelativeTo(null);
        fMainMenu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fMainMenu.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpSecondary = new javax.swing.JLayeredPane();
        bEmpresas = new javax.swing.JButton();
        bProductos = new javax.swing.JButton();
        lParametros = new javax.swing.JLabel();
        lMantenimientos = new javax.swing.JLabel();
        lCaja = new javax.swing.JLabel();
        lPersonas = new javax.swing.JButton();
        lRecepciones = new javax.swing.JButton();
        bFacturaProv = new javax.swing.JButton();
        bFacturaVenta = new javax.swing.JButton();

        lpSecondary.setBackground(new java.awt.Color(255, 255, 255));
        lpSecondary.setPreferredSize(new java.awt.Dimension(330, 350));

        bEmpresas.setBackground(new java.awt.Color(255, 255, 255));
        bEmpresas.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bEmpresas.setText("Empresas");
        bEmpresas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        bEmpresas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEmpresas.setFocusPainted(false);
        bEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpresasActionPerformed(evt);
            }
        });

        bProductos.setBackground(new java.awt.Color(255, 255, 255));
        bProductos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bProductos.setText("Productos");
        bProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 95, 200)));
        bProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bProductos.setFocusPainted(false);

        lParametros.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lParametros.setText("PARÁMETROS");

        lMantenimientos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lMantenimientos.setText("MANTENIMIENTOS");

        lCaja.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lCaja.setText("CAJA");

        lPersonas.setBackground(new java.awt.Color(255, 255, 255));
        lPersonas.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lPersonas.setText("Personas");
        lPersonas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        lPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lPersonas.setFocusPainted(false);

        lRecepciones.setBackground(new java.awt.Color(255, 255, 255));
        lRecepciones.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lRecepciones.setText("Recepciones");
        lRecepciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 95, 200)));
        lRecepciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lRecepciones.setFocusPainted(false);

        bFacturaProv.setBackground(new java.awt.Color(255, 255, 255));
        bFacturaProv.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bFacturaProv.setText("Factura Proveedor");
        bFacturaProv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        bFacturaProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFacturaProv.setFocusPainted(false);
        bFacturaProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFacturaProvActionPerformed(evt);
            }
        });

        bFacturaVenta.setBackground(new java.awt.Color(255, 255, 255));
        bFacturaVenta.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bFacturaVenta.setText("Factura Venta");
        bFacturaVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        bFacturaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bFacturaVenta.setFocusPainted(false);

        lpSecondary.setLayer(bEmpresas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lParametros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lMantenimientos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lCaja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lPersonas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lRecepciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bFacturaProv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bFacturaVenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpSecondaryLayout = new javax.swing.GroupLayout(lpSecondary);
        lpSecondary.setLayout(lpSecondaryLayout);
        lpSecondaryLayout.setHorizontalGroup(
            lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSecondaryLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpSecondaryLayout.createSequentialGroup()
                        .addComponent(bEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bFacturaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCaja)
                    .addComponent(lMantenimientos)
                    .addComponent(lParametros)
                    .addGroup(lpSecondaryLayout.createSequentialGroup()
                        .addComponent(lPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lRecepciones, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bFacturaProv, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lpSecondaryLayout.setVerticalGroup(
            lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSecondaryLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lParametros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lMantenimientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRecepciones, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFacturaProv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFacturaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lpSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lpSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpresasActionPerformed
        fMainMenu.dispose();
        Empresas fEmpresa = new Empresas(conexion);
        fEmpresa.run();
    }//GEN-LAST:event_bEmpresasActionPerformed

    private void bFacturaProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFacturaProvActionPerformed
        fMainMenu.dispose();
        FacturasProv fFacturaProv = new FacturasProv(conexion);
        fFacturaProv.run();
    }//GEN-LAST:event_bFacturaProvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEmpresas;
    private javax.swing.JButton bFacturaProv;
    private javax.swing.JButton bFacturaVenta;
    private javax.swing.JButton bProductos;
    private javax.swing.JLabel lCaja;
    private javax.swing.JLabel lMantenimientos;
    private javax.swing.JLabel lParametros;
    private javax.swing.JButton lPersonas;
    private javax.swing.JButton lRecepciones;
    private javax.swing.JLayeredPane lpSecondary;
    // End of variables declaration//GEN-END:variables
}
