/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.abm;

import db.bdOracle;
import forms.Login;
import forms.MenuPrincipal;
import models.Empresa;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.DefaultListModel;

/**
 *
 * @author Nelba Barreto
 */
public class Empresas extends javax.swing.JPanel {
    private final JFrame fEmpresa = new JFrame("Carga Empresa");
    private List<Empresa> empresas;
    private final bdOracle conexion;
    private String msg;

    public Empresas(bdOracle bd) {
        conexion = bd;
        initComponents();
        lpSecondary.setSize(350, 350);
        lpSecondary.setOpaque(true);
        tfId.setBorder(BorderFactory.createCompoundBorder(
        tfId.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        tfDescripcion.setBorder(BorderFactory.createCompoundBorder(
        tfDescripcion.getBorder(), 
        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        Color color1 = new Color(84, 52, 178);
        Color color2 = new Color(172, 95, 200);
        GradientPaint gp = new GradientPaint(0, 0, color1, 0, h, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
    }
    
    public void run() {
        Empresas panel = new Empresas(conexion);
        fEmpresa.add(panel);
        fEmpresa.setSize(400, 400);
        fEmpresa.setLocationRelativeTo(null);
        fEmpresa.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fEmpresa.setVisible(true);
    }

    private DefaultListModel populateList() {
        DefaultListModel<String> rowValues = new DefaultListModel<>();
        try {
            empresas = new ArrayList<Empresa>();
            Empresa currentEmpresa = null;
            int i = 0;
            String query = "SELECT EMPR_ID_EMPRESA, EMPR_DESCRIPCION FROM EMPRESAS ORDER BY EMPR_ID_EMPRESA DESC";
            
            ResultSet rset = conexion.sql(query);
            while (rset.next()) {
                currentEmpresa = new Empresa(Integer.parseInt(rset.getString(1)), rset.getString(2));
                empresas.add(currentEmpresa);
                
                rowValues.add(i, rset.getString(2));
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rowValues;
    }
    
    private void setMsg(int response) {
        lMsg.setVisible(true);
        lMsg.setText(msg);
        if (response == 1) {
            lMsg.setForeground(Color.GREEN);
        } else {
            lMsg.setForeground(Color.RED);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpSecondary = new javax.swing.JLayeredPane();
        lId = new javax.swing.JLabel();
        lId1 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        bCreate = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lEmpresa = new javax.swing.JList<>(populateList());
        lMsg = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 400));

        lpSecondary.setBackground(new java.awt.Color(255, 255, 255));
        lpSecondary.setFocusCycleRoot(true);
        lpSecondary.setPreferredSize(new java.awt.Dimension(350, 350));

        lId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lId.setLabelFor(tfId);
        lId.setText("Id Empresa");

        lId1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lId1.setLabelFor(tfDescripcion);
        lId1.setText("Descripción");

        tfDescripcion.setBackground(new java.awt.Color(229, 232, 237));
        tfDescripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tfDescripcion.setBorder(null);
        tfDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tfId.setBackground(new java.awt.Color(229, 232, 237));
        tfId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tfId.setBorder(null);
        tfId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfId.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfId.setEnabled(false);

        bCreate.setBackground(new java.awt.Color(255, 255, 255));
        bCreate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bCreate.setText("Insertar");
        bCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        bCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCreate.setFocusPainted(false);
        bCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateActionPerformed(evt);
            }
        });

        bUpdate.setBackground(new java.awt.Color(255, 255, 255));
        bUpdate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bUpdate.setText("Actualizar");
        bUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        bUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUpdate.setFocusPainted(false);
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bDelete.setBackground(new java.awt.Color(255, 255, 255));
        bDelete.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bDelete.setText("Eliminar");
        bDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
        bDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDelete.setFocusPainted(false);
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        lEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 95, 200)));
        lEmpresa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lEmpresa.setSelectionBackground(new java.awt.Color(229, 232, 237));
        lEmpresa.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lEmpresaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lEmpresa);

        lMsg.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        bVolver.setBackground(new java.awt.Color(255, 255, 255));
        bVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/goBack.png"))); // NOI18N
        bVolver.setBorder(null);
        bVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVolver.setNextFocusableComponent(tfId);
        bVolver.setPreferredSize(new java.awt.Dimension(30, 30));
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        lpSecondary.setLayer(lId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lId1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(tfDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(tfId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bCreate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(lMsg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpSecondary.setLayer(bVolver, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpSecondaryLayout = new javax.swing.GroupLayout(lpSecondary);
        lpSecondary.setLayout(lpSecondaryLayout);
        lpSecondaryLayout.setHorizontalGroup(
            lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSecondaryLayout.createSequentialGroup()
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpSecondaryLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lpSecondaryLayout.createSequentialGroup()
                                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lId)
                                    .addComponent(lId1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfId)
                            .addComponent(tfDescripcion)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpSecondaryLayout.createSequentialGroup()
                                .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpSecondaryLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(lpSecondaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lpSecondaryLayout.setVerticalGroup(
            lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpSecondaryLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpSecondaryLayout.createSequentialGroup()
                        .addComponent(lId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lId1)
                        .addGap(6, 6, 6)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lpSecondaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lpSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lEmpresaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lEmpresaValueChanged
        if(lEmpresa.getSelectedValue() != null) {
            String descripcion = lEmpresa.getSelectedValue();
            int index = lEmpresa.getSelectedIndex();
            String id = String.valueOf(empresas.get(index).getId());

            tfId.setText(id);
            tfDescripcion.setText(descripcion);
        }
    }//GEN-LAST:event_lEmpresaValueChanged

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        try {
            int id = Integer.parseInt(tfId.getText());

            int response = conexion.fc_dele_empresa(id);
            if (response == 1) {
                lEmpresa.clearSelection();
                lEmpresa.setModel(populateList());
                tfDescripcion.setText("");
                tfId.setText("");
                msg = "Registro eliminado correctamente";
            } else {
                msg = "No se pudo eliminar el registro";
            }
            setMsg(response);
        } catch (SQLException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        try {
            int id = Integer.parseInt(tfId.getText());
            String descripcion = tfDescripcion.getText();

            int response = conexion.fc_actu_empresa(id, descripcion);
            if (response == 1) {
                lEmpresa.setModel(populateList());
                msg = "Registro actualizado correctamente";
            } else {
                msg = "No se pudo actualizar el registro";
            }
            setMsg(response);
        } catch (SQLException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        try {
            String descripcion = tfDescripcion.getText();
            if(descripcion.equals("")) {
                msg = "El campo descripción no puede estar vacío";
                setMsg(0);
            } else {
                int response = conexion.fc_inse_empresa(conexion.recuSigteNumero("EMPRESAS"), descripcion);
                if (response == 1) {
                    lEmpresa.clearSelection();
                    lEmpresa.setModel(populateList());
                    tfDescripcion.setText("");
                    tfId.setText("");
                    msg = "Registro insertado correctamente";
                } else {
                    msg = "No se pudo insertar el registro";
                }
                setMsg(response);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCreateActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        fEmpresa.dispose();
        MenuPrincipal fMainMenu = new MenuPrincipal(conexion);
        fMainMenu.run();
    }//GEN-LAST:event_bVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bUpdate;
    private javax.swing.JButton bVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lEmpresa;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lId1;
    private javax.swing.JLabel lMsg;
    private javax.swing.JLayeredPane lpSecondary;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfId;
    // End of variables declaration//GEN-END:variables
}
