/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.ABM;

import db.bdOracle;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BorderFactory;
import utils.Formulario;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JFrame;
import models.Ciudad;

/**
 *
 * @author Nelba Barreto
 */
public class Personas extends javax.swing.JPanel {

    private List<Ciudad> ciudades;
    private static bdOracle conexion;
    private String msg;

    public Personas(bdOracle bd) {
        conexion = bd;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEmpresas = new javax.swing.JPanel();
        laCodPersona = new javax.swing.JLabel();
        laCedula = new javax.swing.JLabel();
        tfNombre1 = new javax.swing.JTextField();
        bCreate = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        lMsg = new javax.swing.JLabel();
        tfApellido1 = new javax.swing.JTextField();
        tfApellido2 = new javax.swing.JTextField();
        tfNombre2 = new javax.swing.JTextField();
        tfCedula = new javax.swing.JTextField();
        tfCodPersona = new javax.swing.JTextField();
        bConsultar = new javax.swing.JButton();
        laApellido1 = new javax.swing.JLabel();
        laApellido2 = new javax.swing.JLabel();
        laNombre2 = new javax.swing.JLabel();
        laNombre1 = new javax.swing.JLabel();
        bMore = new javax.swing.JButton();
        cxCiudades = new javax.swing.JComboBox<>();
        laCiudadNto = new javax.swing.JLabel();
        bReload = new javax.swing.JButton();
        bClean = new javax.swing.JButton();

        pEmpresas.setBackground(new java.awt.Color(255, 255, 255));

        laCodPersona.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        laCodPersona.setLabelFor(tfCodPersona);
        laCodPersona.setText("Código de Persona");

        laCedula.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        laCedula.setLabelFor(tfCedula);
        laCedula.setText("Cédula");

        tfNombre1.setBackground(new java.awt.Color(229, 232, 237));
        tfNombre1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tfNombre1.setBorder(null);
        tfNombre1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfNombre1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfNombre1.setBorder(BorderFactory.createCompoundBorder(
            tfNombre1.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

    bCreate.setBackground(new java.awt.Color(255, 255, 255));
    bCreate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bCreate.setText("Insertar");
    bCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bCreate.setFocusPainted(false);
    bCreate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bCreateActionPerformed(evt);
        }
    });

    bUpdate.setBackground(new java.awt.Color(255, 255, 255));
    bUpdate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bUpdate.setText("Actualizar");
    bUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bUpdate.setFocusPainted(false);
    bUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bUpdateActionPerformed(evt);
        }
    });

    bDelete.setBackground(new java.awt.Color(255, 255, 255));
    bDelete.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bDelete.setText("Eliminar");
    bDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bDelete.setFocusPainted(false);
    bDelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bDeleteActionPerformed(evt);
        }
    });

    lMsg.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

    tfApellido1.setBackground(new java.awt.Color(229, 232, 237));
    tfApellido1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tfApellido1.setBorder(null);
    tfApellido1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tfApellido1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
    tfApellido1.setBorder(BorderFactory.createCompoundBorder(
        tfApellido1.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

tfApellido2.setBackground(new java.awt.Color(229, 232, 237));
tfApellido2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
tfApellido2.setBorder(null);
tfApellido2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
tfApellido2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
tfApellido2.setBorder(BorderFactory.createCompoundBorder(
    tfApellido2.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

    tfNombre2.setBackground(new java.awt.Color(229, 232, 237));
    tfNombre2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tfNombre2.setBorder(null);
    tfNombre2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tfNombre2.setDisabledTextColor(new java.awt.Color(51, 51, 51));
    tfNombre2.setBorder(BorderFactory.createCompoundBorder(
        tfNombre2.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

tfCedula.setBackground(new java.awt.Color(229, 232, 237));
tfCedula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
tfCedula.setBorder(null);
tfCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
tfCedula.setDisabledTextColor(new java.awt.Color(51, 51, 51));
tfCedula.setBorder(BorderFactory.createCompoundBorder(
    tfCedula.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

    tfCodPersona.setBackground(new java.awt.Color(229, 232, 237));
    tfCodPersona.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tfCodPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    tfCodPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tfCodPersona.setDisabledTextColor(new java.awt.Color(51, 51, 51));
    tfCodPersona.setBorder(BorderFactory.createCompoundBorder(
        tfCodPersona.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

bConsultar.setBackground(new java.awt.Color(255, 255, 255));
bConsultar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
bConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/search.png"))); // NOI18N
bConsultar.setToolTipText("Consultar");
bConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
bConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
bConsultar.setFocusPainted(false);
bConsultar.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        bConsultarActionPerformed(evt);
    }
    });

    laApellido1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    laApellido1.setText("Apellido 1");

    laApellido2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    laApellido2.setLabelFor(tfApellido2);
    laApellido2.setText("Apellido 2");

    laNombre2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    laNombre2.setLabelFor(tfNombre2);
    laNombre2.setText("Nombre 2");

    laNombre1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    laNombre1.setLabelFor(tfNombre2);
    laNombre1.setText("Nombre 1");

    bMore.setBackground(new java.awt.Color(255, 255, 255));
    bMore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/more.png"))); // NOI18N
    bMore.setToolTipText("Cargar Ciudad");
    bMore.setBorder(null);
    bMore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bMore.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bMoreActionPerformed(evt);
        }
    });

    cxCiudades.setBackground(new java.awt.Color(229, 232, 237));
    cxCiudades.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    cxCiudades.setPreferredSize(new java.awt.Dimension(1, 15));
    cxCiudades.setPreferredSize(new java.awt.Dimension(1, 15));
    ciudades = Formulario.Ciudades.populateComboBox(cxCiudades, conexion);

    laCiudadNto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    laCiudadNto.setLabelFor(tfCedula);
    laCiudadNto.setText("Ciudad de Nacimiento");

    bReload.setBackground(new java.awt.Color(255, 255, 255));
    bReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/reload.png"))); // NOI18N
    bReload.setToolTipText("Agregar Nuevo ");
    bReload.setBorder(null);
    bReload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bReload.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bReloadActionPerformed(evt);
        }
    });

    bClean.setBackground(new java.awt.Color(255, 255, 255));
    bClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/broom.png"))); // NOI18N
    bClean.setToolTipText("Limpiar");
    bClean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 95, 200)));
    bClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bClean.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bCleanActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout pEmpresasLayout = new javax.swing.GroupLayout(pEmpresas);
    pEmpresas.setLayout(pEmpresasLayout);
    pEmpresasLayout.setHorizontalGroup(
        pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pEmpresasLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(laNombre1))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEmpresasLayout.createSequentialGroup()
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(laNombre2)
                                .addComponent(laApellido2)
                                .addComponent(tfApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pEmpresasLayout.createSequentialGroup()
                                    .addComponent(cxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bMore))
                                .addGroup(pEmpresasLayout.createSequentialGroup()
                                    .addComponent(laCiudadNto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bReload))
                                .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bClean)
                                    .addComponent(tfNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(32, 32, 32))
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(laApellido1)
                        .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(laCedula)
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(laCodPersona)
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addComponent(tfCodPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(bConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    pEmpresasLayout.setVerticalGroup(
        pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pEmpresasLayout.createSequentialGroup()
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(laCodPersona)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfCodPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(bClean)))
            .addGap(18, 18, 18)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(laNombre1)
                .addComponent(laNombre2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(laApellido1)
                        .addComponent(laApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(laCedula)
                        .addComponent(laCiudadNto)))
                .addComponent(bReload, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(bMore))
            .addGap(18, 18, 18)
            .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(17, 17, 17)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(60, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 595, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 447, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed
        try {
            if (tfCodPersona.getText().equals("")) {
                msg = "Código de Persona no puede estar vacío";
                Formulario.General.setMsg(0, lMsg, msg);
            } else {
                // Código de Persona
                int codPersona = Integer.parseInt(tfCodPersona.getText());
                String query = "SELECT pers_cod_persona, pers_nombre1, pers_nombre2, pers_apellido1, "
                        + "pers_apellido2, pers_nro_cedula FROM PERSONAS WHERE pers_cod_persona = " + codPersona;

                ResultSet rset = conexion.sql(query);

                if (Formulario.General.resultSetIsEmpty(rset) == true) {
                    msg = "No se encuentra ninguna Persona con ese código";
                    Formulario.General.setMsg(0, lMsg, msg);
                } else {
                    lMsg.setText("");
                    do {
                        tfCodPersona.setText(rset.getString(1));
                        tfNombre1.setText(rset.getString(2));
                        tfNombre2.setText(rset.getString(3));
                        tfApellido1.setText(rset.getString(4));
                        tfApellido2.setText(rset.getString(5));
                        tfCedula.setText(rset.getString(6));
                        cxCiudades.setSelectedIndex(0);
                    } while (rset.next());
                }
            }
        } catch (SQLException ex) {
            msg = "Error al consultar";
            Formulario.General.setMsg(0, lMsg, msg);
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            msg = "Error al consultar";
            Formulario.General.setMsg(0, lMsg, msg);
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        };
    }//GEN-LAST:event_bConsultarActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        try {
            int codigo = Integer.parseInt(tfCodPersona.getText());

            int response = conexion.fc_dele_persona(codigo);
            if (response == 1) {
                tfCodPersona.setText("");
                tfNombre1.setText("");
                tfNombre2.setText("");
                tfApellido1.setText("");
                tfApellido2.setText("");
                tfCedula.setText("");
                cxCiudades.setSelectedIndex(0);
                msg = "Registro eliminado correctamente";
            } else {
                msg = "No se pudo eliminar el registro";
            }
            Formulario.General.setMsg(response, lMsg, msg);
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        try {
            int codigo = Integer.parseInt(tfCodPersona.getText());
            String nombre1 = tfNombre1.getText();
            String nombre2 = tfNombre2.getText();
            String apellido1 = tfApellido1.getText();
            String apellido2 = tfApellido2.getText();
            String cedula = tfCedula.getText();
            int index = cxCiudades.getSelectedIndex();
            int idCiudad = ciudades.get(index).getCodigo();

            int response = conexion.fc_actu_persona(codigo, nombre1, nombre2,
                    apellido1, apellido2, cedula, idCiudad);
            if (response == 1) {
                msg = "Registro actualizado correctamente";
            } else {
                msg = "No se pudo actualizar el registro";
            }
            Formulario.General.setMsg(response, lMsg, msg);
        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        try {
            String nombre1 = tfNombre1.getText();
            String nombre2 = tfNombre2.getText();
            String apellido1 = tfApellido1.getText();
            String apellido2 = tfApellido2.getText();
            String cedula = tfCedula.getText();
            int index = cxCiudades.getSelectedIndex();
            int idCiudad = ciudades.get(index).getCodigo();

            int response = conexion.fc_inse_persona(conexion.recuSigteNumero("PERSONAS"),
                    nombre1, nombre2, apellido1, apellido2, cedula, idCiudad);
            if (response == 1) {
                tfCodPersona.setText("");
                tfNombre1.setText("");
                tfNombre2.setText("");
                tfApellido1.setText("");
                tfApellido2.setText("");
                tfCedula.setText("");
                cxCiudades.setSelectedIndex(0);
                msg = "Registro insertado correctamente";
            } else {
                msg = "No se pudo insertar el registro";
            }
            Formulario.General.setMsg(response, lMsg, msg);

        } catch (SQLException ex) {
            Logger.getLogger(Personas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCreateActionPerformed

    private void bMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoreActionPerformed
        JFrame frame = new JFrame();
        Ciudades pCiudades = new Ciudades(conexion);
        frame.add(pCiudades);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(600, 400);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_bMoreActionPerformed

    private void bReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReloadActionPerformed
        ciudades = Formulario.Ciudades.populateComboBox(cxCiudades, conexion);
    }//GEN-LAST:event_bReloadActionPerformed

    private void bCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCleanActionPerformed
        cxCiudades.setSelectedIndex(0);
        tfApellido1.setText("");
        tfApellido2.setText("");
        tfNombre1.setText("");
        tfNombre2.setText("");
        tfCedula.setText("");
        tfCodPersona.setText("");
    }//GEN-LAST:event_bCleanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClean;
    private javax.swing.JButton bConsultar;
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bMore;
    private javax.swing.JButton bReload;
    private javax.swing.JButton bUpdate;
    private javax.swing.JComboBox<String> cxCiudades;
    private javax.swing.JLabel lMsg;
    private javax.swing.JLabel laApellido1;
    private javax.swing.JLabel laApellido2;
    private javax.swing.JLabel laCedula;
    private javax.swing.JLabel laCiudadNto;
    private javax.swing.JLabel laCodPersona;
    private javax.swing.JLabel laNombre1;
    private javax.swing.JLabel laNombre2;
    private javax.swing.JPanel pEmpresas;
    private javax.swing.JTextField tfApellido1;
    private javax.swing.JTextField tfApellido2;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfCodPersona;
    private javax.swing.JTextField tfNombre1;
    private javax.swing.JTextField tfNombre2;
    // End of variables declaration//GEN-END:variables
}
