/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.ABM;

import db.bdOracle;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BorderFactory;
import models.Producto;
import utils.Formulario;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author HP
 */
public class Productos extends javax.swing.JPanel {
    private List<Producto> productos;
    private static bdOracle conexion;
    private String msg;
    
    public Productos(bdOracle bd) {
        conexion = bd;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pEmpresas = new javax.swing.JPanel();
        lId = new javax.swing.JLabel();
        lId1 = new javax.swing.JLabel();
        tfCodProducto = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lProductos = new javax.swing.JList<>();
        bCreate = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        lMsg = new javax.swing.JLabel();

        pEmpresas.setBackground(new java.awt.Color(255, 255, 255));

        lId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lId.setText("Código de Producto");

        lId1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lId1.setText("Descripción");

        tfCodProducto.setBackground(new java.awt.Color(229, 232, 237));
        tfCodProducto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tfCodProducto.setBorder(null);
        tfCodProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfCodProducto.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfCodProducto.setEnabled(false);
        tfCodProducto.setBorder(BorderFactory.createCompoundBorder(
            tfCodProducto.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

    tfDescripcion.setBackground(new java.awt.Color(229, 232, 237));
    tfDescripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
    tfDescripcion.setBorder(null);
    tfDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tfDescripcion.setBorder(BorderFactory.createCompoundBorder(
        tfDescripcion.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));

lProductos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(172, 95, 200), 1, true));
lProductos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
lProductos.setSelectionBackground(new java.awt.Color(229, 232, 237));
lProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
    public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        lProductosValueChanged(evt);
    }
    });
    productos = Formulario.Productos.populateList(lProductos, conexion);
    jScrollPane1.setViewportView(lProductos);

    bCreate.setBackground(new java.awt.Color(255, 255, 255));
    bCreate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bCreate.setText("Insertar");
    bCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bCreate.setFocusPainted(false);
    bCreate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bCreateActionPerformed(evt);
        }
    });

    bUpdate.setBackground(new java.awt.Color(255, 255, 255));
    bUpdate.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bUpdate.setText("Actualizar");
    bUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bUpdate.setFocusPainted(false);
    bUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bUpdateActionPerformed(evt);
        }
    });

    bDelete.setBackground(new java.awt.Color(255, 255, 255));
    bDelete.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
    bDelete.setText("Eliminar");
    bDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 52, 178)));
    bDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    bDelete.setFocusPainted(false);
    bDelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bDeleteActionPerformed(evt);
        }
    });

    lMsg.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

    javax.swing.GroupLayout pEmpresasLayout = new javax.swing.GroupLayout(pEmpresas);
    pEmpresas.setLayout(pEmpresasLayout);
    pEmpresasLayout.setHorizontalGroup(
        pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pEmpresasLayout.createSequentialGroup()
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfCodProducto)
                        .addComponent(tfDescripcion)
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lId1)
                                .addComponent(lId))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(50, 50, 50))
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pEmpresasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27))
    );
    pEmpresasLayout.setVerticalGroup(
        pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pEmpresasLayout.createSequentialGroup()
            .addGap(46, 46, 46)
            .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(pEmpresasLayout.createSequentialGroup()
                    .addComponent(lId)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tfCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)
                    .addComponent(lId1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addGroup(pEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1))
            .addContainerGap(41, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 567, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 358, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void bCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateActionPerformed
        try {
            String descripcion = tfDescripcion.getText();
            if (descripcion.equals("")) {
                msg = "El campo descripción no puede estar vacío";
                Formulario.General.setMsg(0, lMsg, msg);
            } else {
                int response = conexion.fc_inse_producto(conexion.recuSigteNumero("PRODUCTOS"), descripcion);
                if (response == 1) {
                    lProductos.clearSelection();
                    productos = Formulario.Productos.populateList(lProductos, conexion);
                    tfDescripcion.setText("");
                    tfCodProducto.setText("");
                    msg = "Registro insertado correctamente";
                } else {
                    msg = "No se pudo insertar el registro";
                }
                Formulario.General.setMsg(response, lMsg, msg);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCreateActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        try {
            int id = Integer.parseInt(tfCodProducto.getText());
            String descripcion = tfDescripcion.getText();

            int response = conexion.fc_actu_producto(id, descripcion);
            if (response == 1) {
                productos = Formulario.Productos.populateList(lProductos, conexion);
                msg = "Registro actualizado correctamente";
            } else {
                msg = "No se pudo actualizar el registro";
            }
            Formulario.General.setMsg(response, lMsg, msg);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        try {
            int codigo = Integer.parseInt(tfCodProducto.getText());

            int response = conexion.fc_dele_producto(codigo);
            if (response == 1) {
                lProductos.clearSelection();
                productos = Formulario.Productos.populateList(lProductos, conexion);
                tfDescripcion.setText("");
                tfCodProducto.setText("");
                msg = "Registro eliminado correctamente";
            } else {
                msg = "No se pudo eliminar el registro";
            }
            Formulario.General.setMsg(response, lMsg, msg);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void lProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lProductosValueChanged
        if (lProductos.getSelectedValue() != null) {
            String descripcion = lProductos.getSelectedValue();
            int index = lProductos.getSelectedIndex();
            String id = String.valueOf(productos.get(index).getCodigo());

            tfCodProducto.setText(id);
            tfDescripcion.setText(descripcion);
        }
    }//GEN-LAST:event_lProductosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lId1;
    private javax.swing.JLabel lMsg;
    private javax.swing.JList<String> lProductos;
    private javax.swing.JPanel pEmpresas;
    private javax.swing.JTextField tfCodProducto;
    private javax.swing.JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables
}
